config/routes.rb
Hackbyrd::Application.routes.draw do
  root :to => 'hackbyrd#home'

  match '/about',       to: 'hackbyrd#about',       via: 'get'
  match '/fiscalnote',  to: 'hackbyrd#fiscalnote',  via: 'get'
  match '/portfolio',   to: 'hackbyrd#portfolio',   via: 'get'
  match '/contact',     to: 'hackbyrd#contact',     via: 'get'
  match '/snake',       to: 'hackbyrd#snake',       via: 'get'
  match '/andrea',      to: 'hackbyrd#andrea',      via: 'get'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hackbyrd_controller.rb
class HackbyrdController < ApplicationController

  def home
  end

  def about
  end

  def fiscalnote
  end

  def portfolio
  end

  def contact
  end

  def snake
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hackbyrd/about.html.erb
<%# Extra stylesheets (CSS) just for this page. %>
<% content_for :extra_stylesheets do %>
  <%= stylesheet_link_tag "about" %>
  <%= stylesheet_link_tag "animate" %>
<% end %>

<%# Extra Javascript just for this page. %>
<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "about.js" %>
  <%= javascript_include_tag "wow.min.js" %>
<% end %>

<%# Activate WOW %>
<script>new WOW().init();</script>

<%# fixed side navigation %>
<%= render "layouts/side_navigation" %>

<div id="about-background" class="background-height">

  <%# text %>
  <div id="about-background-left" class="background-height">
    <h1 class="wow fadeInLeft" data-wow-duration=".75s" data-wow-delay=".75s">Engineer</h1>
    <h1 class="wow fadeInLeft" data-wow-duration=".75s" data-wow-delay="1.5s">Entreprenuer</h1>
    <h1 class="wow fadeInLeft" data-wow-duration=".75s" data-wow-delay="2.25s">Designer</h1>

    <%# scroll down buttom %>
    <div id="learnmore-box">
      <h2 id="jc-quote" class="wow fadeInLeft" data-wow-duration=".75s" data-wow-delay="3s">The path to success may seem endless, but it's better that way. It just means that there is no limit to how far you can go</h2>
      <button class="wow bounceInLeft" data-wow-duration="1.25s" data-wow-delay="3.75s" id="learnmore-btn">More About Me</button>
    </div>

    <%# Social links %>
    <div id="about-background-left-footer" class="wow bounceInUp" data-wow-duration="1.25s" data-wow-delay="3.75s">

      <%# appears in xs and lg screens %>
      <div class="social-link-box visible-xs-lg">
        <a href="mailto:jxmoneyz@gmail.com"><%= image_tag "social/email_gray.svg", :class => "social-link", :style => "margin-left: 0px;" %></a>
        <a href="https://www.linkedin.com/in/hackbyrd"><%= image_tag "social/linkedin_gray.svg", :class => "social-link" %></a>
        <a href="https://github.com/Hackbyrd"><%= image_tag "social/github_gray.svg", :class => "social-link" %></a>
        <a href="https://www.facebook.com/hackbyrd"><%= image_tag "social/facebook_gray.svg", :class => "social-link" %></a>
        <a href="https://twitter.com/Hackbyrd"><%= image_tag "social/twitter_gray.svg", :class => "social-link" %></a>
        <a href="https://plus.google.com/u/0/+JonathanChenHackbyrd"><%= image_tag "social/googleplus_gray.svg", :class => "social-link" %></a>
      </div>

      <%# appears in md screens %>
      <div class="social-link-box visible-md">
        <a href="mailto:jxmoneyz@gmail.com"><%= image_tag "social/email_gray.svg", :class => "social-link", :style => "margin-left: 0px;" %></a>
        <a href="https://www.linkedin.com/in/hackbyrd"><%= image_tag "social/linkedin_gray.svg", :class => "social-link" %></a>
        <a href="https://github.com/Hackbyrd"><%= image_tag "social/github_gray.svg", :class => "social-link" %></a>
      </div>
      <div class="social-link-box visible-md">
        <a href="https://www.facebook.com/hackbyrd"><%= image_tag "social/facebook_gray.svg", :class => "social-link", :style => "margin-left: 0px;" %></a>
        <a href="https://twitter.com/Hackbyrd"><%= image_tag "social/twitter_gray.svg", :class => "social-link" %></a>
        <a href="https://plus.google.com/u/0/+JonathanChenHackbyrd"><%= image_tag "social/googleplus_gray.svg", :class => "social-link" %></a>
      </div>

      <%# appears in sm screens %>
      <div class="social-link-box visible-sm">
        <a href="mailto:jxmoneyz@gmail.com"><%= image_tag "social/email_gray.svg", :class => "social-link", :style => "margin-left: 0px;" %></a>
        <a href="https://www.linkedin.com/in/hackbyrd"><%= image_tag "social/linkedin_gray.svg", :class => "social-link" %></a>
      </div>
      <div class="social-link-box visible-sm">
        <a href="https://www.facebook.com/hackbyrd"><%= image_tag "social/facebook_gray.svg", :class => "social-link", :style => "margin-left: 0px;" %></a>
        <a href="https://twitter.com/Hackbyrd"><%= image_tag "social/twitter_gray.svg", :class => "social-link" %></a>
      </div>
      <div class="social-link-box visible-sm">
        <a href="https://github.com/Hackbyrd"><%= image_tag "social/github_gray.svg", :class => "social-link", :style => "margin-left: 0px;" %></a>
        <a href="https://plus.google.com/u/0/+JonathanChenHackbyrd"><%= image_tag "social/googleplus_gray.svg", :class => "social-link" %></a>
      </div>
    </div>
  </div>

  <%# background image %>
  <div id="about-background-right" class="background-height"></div>

</div>

<%# content %>
<div id="about-content-container">
  <div id="about-content-diagonal">

    <%# Introduction %>
    <div class="about-content-inner wow fadeIn" style="margin-bottom: 50px;">
      <h1>Hello, I'm <b class="text-red">Jonathan</b> Chen</h1>
    </div>

    <div class="about-content-inner wow fadeIn">
      <%= image_tag "about/maryland-state.png" %>
    </div>

    <div class="about-content-inner wow fadeIn" style="min-height: 10px">
      <h2 style="display: inline">I was born and raised in Montgomery County, <b class="text-red">Maryland</b></h2>
    </div>

    <%# Early Education %>
    <div class="about-content-inner wow fadeIn">
      <h2>where I attended...</h2>
      <%= image_tag "about/travilah.jpg", :class => "school-img" %>
      <%= image_tag "about/frost.jpg", :class => "school-img" %>
      <%= image_tag "about/wootton.jpg", :class => "school-img", :style => "margin-right: 0px;" %>
      <br/>
      <span class="img-caption"><b class="text-red">Travilah</b><br/>Elementary School</span>
      <span class="img-caption"><b class="text-red">Frost</b><br/>Middle School</span>
      <span class="img-caption" style="margin-right: 0px"><b class="text-red">Wootton</b><br/>High School</span>
    </div>

    <div class="about-content-inner wow fadeIn">
      <div class="bar redbar float-center" style="margin-top: 35px"></div>
    </div>

    <%# Family %>
    <div class="about-content-inner wow fadeIn" style="min-height: 10px;">
      <h2>I grew up with a loving <b class="text-red">family</b></h2>
    </div>

    <div class="about-content-inner wow fadeIn" style="margin-bottom: 0px;">
      <%= image_tag "about/mom_me.jpg", :class => "family-img gray" %>
      <%= image_tag "about/dad_me.jpg", :class => "family-img red", :style => "margin-right: 0px;" %>
    </div>

    <div class="about-content-inner wow fadeIn" style="margin-top: 0px; padding-top: 0px;">
      <%= image_tag "about/brother_me.jpg", :class => "family-img red" %>
      <%= image_tag "about/grandparents_me.jpg", :class => "family-img gray", :style => "margin-right: 0px;" %>
    </div>

    <%# Taiwan %>
    <div class="about-content-inner wow fadeIn" style="margin-top: 30px;">
      <h2 class="taiwan-text">We are from <b class="text-red">Taiwan</b></h2>
      <%= image_tag "about/taiwan-island.svg", :class => "taiwan-island" %>
    </div>

    <div class="about-content-inner wow fadeIn">
      <div class="bar graybar" style="margin-top: 0px"></div>
    </div>

    <%# Hobbies %>
    <div class="about-content-inner wow fadeIn">
      <h2>Some <b class="text-red">hobbies</b> of mine include...</h2>
    </div>

    <div class="about-content-inner wow fadeIn">
      <%= image_tag "about/violin.svg", :class => "hobby-img" %>
      <%= image_tag "about/drums.svg", :class => "hobby-img" %>
      <br/>
      <span class="img-caption-hobby">Violin</span>
      <span class="img-caption-hobby red">Drumset</span>
    </div>

    <div class="about-content-inner wow fadeIn">
      <%= image_tag "about/mma.svg", :class => "hobby-img" %>
      <%= image_tag "about/snowboard.svg", :class => "hobby-img" %>
      <br/>
      <span class="img-caption-hobby red">Martial Arts</span>
      <span class="img-caption-hobby">Snowboarding</span>
    </div>

    <div class="about-content-inner wow fadeIn">
      <%= image_tag "about/programming.svg", :class => "hobby-img" %>
      <%= image_tag "about/magic.svg", :class => "hobby-img" %>
      <br/>
      <span class="img-caption-hobby">Hacking</span>
      <span class="img-caption-hobby red">Card Magic</span>
    </div>

    <div class="about-content-inner wow fadeIn">
      <div class="bar graybar" style="margin-top: 0px"></div>
    </div>

    <%# University of Maryland, College Park %>
    <div class="about-content-inner wow fadeIn">
      <h2>I graduated from the <b class="text-red">University of Maryland</b>, College Park</h2>
    </div>

    <div class="about-content-inner wow fadeIn">
      <%= image_tag "about/graduation-me.jpg", :class => "graduation-img" %>
    </div>

    <div class="about-content-inner wow fadeIn">
      <h2>with a bachelor's degree in <b class="text-red">Computer Science.</b></h2>
    </div>

    <div class="about-content-inner wow fadeIn">
      <iframe style="float:right;" width="560" height="315" src="https://www.youtube.com/embed/do5AaJGbFj8" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="about-content-inner wow fadeIn">
      <h2>I delivered the <b class="text-red">Student Commencement Speech</b><br/> at my class Graduation in <b class="text-red">May 2014</b>.</b></h2>
    </div>

    <div class="about-content-inner wow fadeIn">
      <div class="bar graybar" style="margin-top: 0px"></div>
    </div>

    <%# TASA %>
    <div class="about-content-inner wow fadeIn">
      <h2>In college I was <b class="text-red">heavily involved</b> with...</h2>
    </div>

    <div class="about-content-inner wow fadeIn">
      <%= image_tag "about/tasa.jpg", :class => "hobby-img grayborder" %>
      <%= image_tag "about/itasa.jpg", :class => "hobby-img grayborder" %>
      <br/>
      <span class="img-caption-hobby">UMCP TASA</span>
      <span class="img-caption-hobby" style="margin-left:20px">ITASA</span>
    </div>

    <div class="about-content-inner wow fadeIn">
      <div class="bar redbar long"></div>
    </div>

    <%# FiscalNote %>
    <div class="about-content-inner wow fadeIn">
      <h2>Today I live in <b class="text-red">Washington, DC</b></h2>
    </div>

    <div class="about-content-inner wow fadeIn">
      <a href="https://www.fiscalnote.com"><%= image_tag "about/fiscalnote-logo.png", :class => "fn-logo-img" %></a>
    </div>

    <div class="about-content-inner wow fadeIn">
      <h2>Where I serve as the <b class="text-red">CTO</b> & <b class="text-red">Co-Founder</b> of <a href="https://www.fiscalnote.com" class="fiscalnote-link">FiscalNote, Inc.</a></h2>
    </div>

    <div class="about-content-inner wow fadeIn">
      <h2>To be <b class="text-red">continued</b>...</h2>
    </div>

  </div>
</div>

app/views/hackbyrd/contact.html.erb
<h1>UNDER CONSTRUCTION</h1>
<%= image_tag "email.png" %>

app/views/hackbyrd/fiscalnote.html.erb
<%# http://talks.codegram.com/creating-basic-chrome-extensions#/intro %>
<h1>UNDER CONSTRUCTION</h1>

app/views/hackbyrd/home.html.erb
<%# Extra stylesheets (CSS) just for this page. %>
<% content_for :extra_stylesheets do %>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag "animate" %>
  <%= stylesheet_link_tag "home" %>
  <%= stylesheet_link_tag "navigation" %>
  <%= stylesheet_link_tag "link_loading" %>
<% end %>

<%# Extra Javascript just for this page. %>
<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "bootstrap.js" %>
  <%= javascript_include_tag "home.js" %>
  <%= javascript_include_tag "svg_draw.js" %>
  <%= javascript_include_tag "wow.min.js" %>
  <%= javascript_include_tag "modernizr.custom.js" %>
  <%= javascript_include_tag "classie.js" %>
<% end %>

<%# Activate WOW %>
<script>new WOW().init();</script>

<%# loading animation %>
<div class="la-anim-10"></div>

<%# Welcome message %>
<%# <h1 class="animated bounceInDown hidden-xs">Scroll Down <%= image_tag "arrow_down.svg", :class => "arrow-down" %> <%#</h1> %>
<button class="btn btn-lg center-block" id="click-me">Click Me</button>

<%# If user hasn't scrolled yet, remind them %>
<h4 class="wow fadeIn hidden-xs" data-wow-duration=".5s" data-wow-delay="3s">What are you waiting for?</h4>

<%# Logo %>
<%= image_tag "JC_logo-fixed.svg", :id => "jc-logo", :class => "hidden-xs" %>
<%= image_tag "JC_logo-fixed.svg", :class => "visible-xs" %>

<%# Jonathan Chen %>
<%= render "layouts/jonathan_chen" %>

<%# navigation links %>
<section class="color-blue" id="bottom-nav">
  <nav class="cl-effect-blue text-center">
    <a href="<%= about_path %>" class="wow bounceInDown" data-wow-delay="0s">About</a>
    <a href="<%= portfolio_path %>" class="wow bounceInDown" data-wow-delay=".15s">Portfolio</a>
    <a href="<%= fiscalnote_path %>" class="wow bounceInDown" data-wow-delay=".3s">FiscalNote</a>
    <a href="<%= snake_path %>" class="wow bounceInDown" data-wow-delay=".45s">Snake</a>
    <a href="https://medium.com/@Hackbyrd" class="wow bounceInDown" data-wow-delay=".6s">Blog</a>
    <a href="<%= contact_path %>" class="wow bounceInDown" data-wow-delay=".75s">Contact</a>
  </nav>
</section>

<%# button to activate corner loader %>
<div id="la-buttons" style="display: none;">
  <button id="corner" data-anim="la-anim-10" >Corner indicator</button>
</div>

<%# For corner loader %>
<script>
  var loader = document.getElementById('la-anim-6-loader')
    , border = document.getElementById('la-anim-6-border')
    , α = 0
    , π = Math.PI
    , t = 15

    , tdraw;

  function PieDraw() {
    α++;
    α %= 360;
    var r = ( α * π / 180 )
    , x = Math.sin( r ) * 250
    , y = Math.cos( r ) * - 250
    , mid = ( α > 180 ) ? 1 : 0
    , anim = 'M 0 0 v -250 A 250 250 1 '
           + mid + ' 1 '
           +  x  + ' '
           +  y  + ' z';

    loader.setAttribute( 'd', anim );
    border.setAttribute( 'd', anim );
    if( α != 0 )
    tdraw = setTimeout(PieDraw, t); // Redraw
  }

  function PieReset() {
    clearTimeout(tdraw);
    var anim = 'M 0 0 v -250 A 250 250 1 0 1 0 -250 z';
    loader.setAttribute( 'd', anim );
    border.setAttribute( 'd', anim );
  }

  var inProgress = false;

  Array.prototype.slice.call( document.querySelectorAll( '#la-buttons > button' ) ).forEach( function( el, i ) {
    var anim = el.getAttribute( 'data-anim' ),
      animEl = document.querySelector( '.' + anim );

    el.addEventListener( 'click', function() {
      if( inProgress ) return false;
      inProgress = true;
      classie.add( animEl, 'la-animate' );

      if( anim === 'la-anim-6' ) {
        PieDraw();
      }

      setTimeout( function() {
        classie.remove( animEl, 'la-animate' );

        if( anim === 'la-anim-6' ) {
          PieReset();
        }

        inProgress = false;
      }, 6000 );
    } );
  } );
</script>

app/views/hackbyrd/press.html.erb
<h1>UNDER CONTRUCTION</h1>

app/views/hackbyrd/projects.html.erb
<%# Extra stylesheets (CSS) just for this page. %>
<% content_for :extra_stylesheets do %>
  <%= stylesheet_link_tag "projects" %>
<% end %>

<%# Extra Javascript just for this page. %>
<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "projects.js" %>
  <%= javascript_include_tag "particleground.js" %>
  <%= javascript_include_tag "side-navigation.js" %>
<% end %>

<div id="particles" class="window-height">
  <div class="intro">
    <h1><a href="https://www.github.com/hackbyrd" target="_blank"><%= image_tag "social/github_white.svg", :class => "github-link" %></a> Hackbyrd</h1>
    <p>When I'm bored, I make things</p>
    <button class="btn">See Projects</button>
  </div>
</div>

<div class="window-height" style="width: 100%; background-color: white">Coming Soon...</div>
<div class="window-height" style="width: 100%; background-color: red">Coming Soon...</div>
<div class="window-height" style="width: 100%; background-color: blue">Coming Soon...</div>
<div class="window-height" style="width: 100%; background-color: yellow">Coming Soon...</div>
<div class="window-height" style="width: 100%; background-color: purple">Coming Soon...</div>

app/views/hackbyrd/snake.html.erb
<%# Extra stylesheets (CSS) just for this page. %>
<% content_for :extra_stylesheets do %>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag "home" %>
  <%= stylesheet_link_tag "snake" %>
<% end %>

<%# Extra Javascript just for this page. %>
<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "snake.js" %>
<% end %>

<%# Snake game canvas %>
<canvas id="snake_canvas" width="450" height="450"></canvas>

<%# Return Home %>
<a href="<%= root_path %>" style="text-decoration: none;"><button id="return-home" class="btn btn-lg center-block">Return Home</button></a>

app/views/hackbyrd/work.html.erb
<h1>UNDER CONTRUCTION</h1>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41483060-5', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_side_navigation.html.erb
<%# Extra stylesheets (CSS) just for this page. %>
<% content_for :extra_stylesheets do %>
  <%= stylesheet_link_tag "side-navigation" %>
<% end %>

<%# Extra Javascript just for this page. %>
<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "side-navigation.js" %>
<% end %>

<div class="side-navigation right">

  <div class="action-box">
    <%= image_tag "side-navigation/3lines.svg", :class => "action-icon", :id => "three-lines-icon" %>
    <%= image_tag "side-navigation/cross.svg", :class => "action-icon", :id => "cross-icon", :style => "display: none;" %>
  </div>
  <div class="link-box">
    <a href="<%= root_path %>" class="links">Home</a>
    <a href="<%= portfolio_path %>" class="links">Portfolio</a>
    <a href="<%= fiscalnote_path %>" class="links">FiscalNote</a>
    <a href="<%= contact_path %>" class="links">Contact</a>
    <a href="https://medium.com/@Hackbyrd" class="links">Blog</a>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Hackbyrd</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%# Favicon %>
    <%= favicon_link_tag 'hackbyrd.ico' %>

    <%# Stylesheets %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :extra_stylesheets %>

    <%# Prevents Cross Site Request Forgery %>
    <%= csrf_meta_tags %>

    <%# Javascript %>
    <%= javascript_include_tag 'application' %>
    <%= yield :extra_javascripts %>

  </head>

  <body>

    <%# yield main contect %>
    <%= yield %>

    <%# Google Analytics %>
    <%= render "layouts/google_analytics" %>

  </body>
</html>